// <auto-generated />
namespace Remote.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Removed_User_Table : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206222143148_Removed_User_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so1f5omrz8Xfzyfhp1mYfpcdlkREar/Py/D1x2nkInD6yvVF/p4RXe/3mepVzn5999LKuLuosaETNfq/8OviAPqKGq7xur1/l5/rq2eyj9G743t3ui/Y17x30Tr8t23t7H6Uv1mWZTUr64Dwrm/yjdPXpo9dtVeef58u8ztp89jJr27xe4t2csVcqPFp9ejtCPLy7swdC3M2Wy6rNWprhHuIdNPGvQfR1WxOzfJQ+K97ls+f58qKdW2S/yN6ZT+jXj9KvlgXxFr3U1uvcH5z87Xf6+K6bi/4MEce0WUEUUISEK/i7Im86syWvvM7bcE6bj1LXhTDQ2Ex3FBXbqePPu8KghpHvDnDy4y+y1Yqo5HG2fpK+FrY+2X79/ty7EBh3p8GIuySyPRHbZBd551vqmjB9VtRNC3maZJi3k9mi1+x2JDaddSjdlRZHePMCfvfn0kq4nZMODEfDZzSsBfE+j1DHR6gMCK+++3qalVkdEb+TqlwvlkMivOltkQr/ffmkD+Hx3Q7qXfp4zK8tO4qkS/BN7NptYnu3bNthz8fKKjdr4x7vSJOPUiLNZTED37y+btp8IVP5+heVJ2VB43UNvsiWxXnetG+qtzksC7H219fpVpU1zaz8f6liLzD6G1V4T+/fXiEvL7N6Os/qrUX27s43qWT7iuJWenaTmhV2+eyj2aQi9AVNp56/phLuc+/ju77H8fhp3hQXDgT8j2U+heFzQE2bs+V5ZYhNQ/MxMk06c/FF3mYzotBx3Rbn2bSlr6d507CR/MmsXFOT08Ukn50tv1y3q3V73DT5YlJe++N9fHdz/2xpQpwff7nCX564fv0hEJoFDSH/cvlkXZQzi/ezPi8OgQCzKIMTVuQkELiLawvpRbW8JSAl39N8lS8hHm/yxaokYM2Xy9fZZT6M2800DCn2+GmRMeN5FJRPFJPXGfXsdUEd+G+4/uhPYldyd4/+nwAAAP//DuDh5WMLAAA="; }
        }
    }
}
