// <auto-generated />
namespace Remote.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Add_Programs_Users : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206222123487_Add_Programs_Users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so1f5omrz8Xfzyfhp1mYfpcdlkREar/Py/D1x2nkInD6yvVF/p4RXe/3mepVzn5999LKuLuosaETNfq/8OviAPqKGq7xur1/l5/rq2eyj9G743t3ui/Y17x30Tr8t23t7H6Uv1mWZTUr64Dwrm/yjdPXpo9dtVeef58u8ztp89jJr27xe4t2csVcqPFp9ejtCPLy7swdC3M2Wy6rNWprhHuIdNPGvQfR1WxOzfJQ+K97ls+f58qKdW2S/yN6ZT+jXj9KvlgXxFr3U1uvcH5z87Xf6+K6bi40zJAzxVZPXP5qkAE2QZPmzP1HU8YvssrhgnDooqPQ0H6Wv8pIbNPNiJcI6dhP3+7t2z+pq8apCT5Gvf//X1bqeYkDVcJs3WX2Rt7djpuOmqaYFI9bjJodUONjT5Sy9BYZC8nCcROd12RarspgSMp99tDMe7/aIuRm+GZ0H36ioDvBvdUngDbYvUKSC26wgbg3owN8VeZ8EeOV13vam2ZG5i1xvlCEIjDL2vk+8DghvPA5OlKm8lht4r6ssbjfRdiB2DCGaNwIyM+oBcph3VVM45giH23l0NvSuGFFjbO8OWNvHX2SrFSkIz/rqJ+lrMb0n26/f38IuBMbdaUDgLtfZnkhrZhd551vqmjB9VtRNC5s/yaCyTmaLXrPbca3prMO8/WkzvGhewO8+m1kvxLJ5B4aj4TMa1oJUP49Qx+fPdf/NFN5PVmZ1xPqcVOV6sRyyYJveFsvtvy+f9CE8vttBvUsfT6dqyw6zdgl+q+kQIfqQuRhyCBjQTdOx6eWfnRlxZtqH4T794c9MqGTC6Ynq19vMhdf8liIAvdmh1QZF3KfSrebKgxibNpDKIvH18FP9/jXxe2+kSBvOCnZozhq4bdbFu/Wou1amzyM9Y9NtYjnUGp2OcXmsij6wQGks3utpfmnyUUoEuCxm0Pqvr5s2XwjDvf5F5UlZkEy4Bl9ky+I8b9o31dscsSsZpq8fNVo/vGlm5f9LQ8cCo78x/ugFLbcP+ZaXWT2dZ/XWInt358boYFhGOij/fz4c/FkhfDeMew/i/2yHPd9MmGPk5P1jGgJDU5fXoGxWkjZq2pr0Uc8evqTAd1qssrI/gr5avg1TgLQWaPebp/kqX2K2O+O7TVc3miMLvMOkN9HhPcO/vr/dnb1oBLgpABS9/dlHs0lFUy0s63yCG8JDn7l6Xfhfxnpx3/c7+rkIIoNYbzjAjQtJxG/6WYkS+waamGy9tGlbYvOmuHAg4Hgs82nAXrbN2fK8Mszewcg06Wi9L/I2mxHvHddtcZ5NW/p6mjcNJ7B+MivX1OR0MclnZ8sv1+1q3dKQ88WkvPaJAWnZ1D+HwiHOj79ccZbqmxgCoVnQEPIvl0/WRTmzeD/ra/0hEBBDNSWYyxYm5eLaQnpRLW8JSMn31GiPN/liRQm5vPly+Tq7zIdxu5mGIcUePy0ylgSPgvKJYvI6W6xKrwvqwH/D9Ud/ErvSmsHR/xMAAP//0yMFEKgYAAA="; }
        }
    }
}
