// <auto-generated />
namespace Remote.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Added_Command_To_Program : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206222200515_Added_Command_To_Program"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so1f5omrz8Xfzyfhp1mYfpcdlkREar/Py/D1x2nkInD6yvVF/p4RXe/3mepVzn5999LKuLuosaETNfq/8OviAPqKGq7xur1/l5/rq2eyj9G743t3ui/Y17x30Tr8t23t7H6Uv1mWZTUr64Dwrm/yjdPXpo9dtVeef58u8ztp89jJr27xe4t2csVcqPFp9ejtCPLy7swdC3M2Wy6rNWprhHuIdNPGvQfR1WxOzfJQ+K97ls+f58qKdW2S/yN6ZT+jXj9KvlgXxFr3U1us8MrjNvZ5Ui0W2tBT62er48V3HBX3eIF5ts4Jor0gJP/J3Rd50+EReeZ23ITc1H6WuC2HdsWG0KCq2UycZd0U0jAjdHZChx19kqxWRyZMp/SR9LQJ1sv36/eVmITDuToMRd0lkeyKGzS7yzreY0Fn+rKibFpI8yTARJ7NFr9ntSGw661C6K6eO8OYF/O7PpdUtdk46MBwNn9GwFiR1PEIdH6EyoDb03dfTrMzqiOCfVOV6sRxSHpveFnn035dPbg/BypYPxH7Yh/P4bocEXTp7QqQtO6qwO3Gb2L7bxPZu2b/D5o+V5W62Jz0elCYfpUSgy2IG/nt93bT5Qlji9S8qT8qCxusafJEti/O8ad9Ub3PYRhKRr2+VrDJumln5/1LTVGD0Nxqh91TuvklZXmb1dJ7VW4vs3Z33htQxE+8D7P1Uf1993Ur7b1L+wnyffTSbVIS/4OmMxtc0DX1ZeHzX98AeP82b4sKBgD+2zKdwBBxQ0+ZseV4ZgtPQfIxMk858fJG32YwodFy3xXk2benrad40bLt/MivX1OR0MclnZ8sv1+1q3R43Tb6YlNf+eB/f3dw/278Q58dfrvCXJ/xffwiEZkFDyL9cPlkX5czi/SzCQgMgwCwqLoQV+S4E7uLaQnpRLW8JSMn3NF/lSwjbm3yxKglY8+XydXaZD+N2Mw1Dij1+WmTMeB4F5RPF5HVGPXtdUAf+G64/+pPYldz/o/8nAAD///qqDg9zDAAA"; }
        }
    }
}
