// <auto-generated />
namespace Remote.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Added_Remote : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201206231429276_Added_Remote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so1f5omrz8Xfzyfhp1mYfpcdlkREar/Py/D1x2nkInD6yvVF/p4RXe/3mepVzn5999LKuLuosaETNfq/8OviAPqKGq7xur1/l5/rq2eyj9G743t3ui/Y17x30Tr8t23t7H6Uv1mWZTUr64Dwrm/yjdPXpo9dtVeef58u8ztp89jJr27xe4t2csVcqPFp9ejtCPLy7swdC3M2Wy6rNWprhHuIdNPGvQfR1WxOzfJQ+K97ls+f58qKdW2S/yN6ZT+jXj9KvlgXxFr3U1us8MrjNvZ5Ui0W2tBT6Wez4RXZZXDAlOigI932UvspL/rqZFyvhvbFyyu9vmjyrq8WrCn2E3/z+r6t1PQX5qujXb7L6Im9DlB7fdYy5kV218x9x6889t/5kkV/9MHoe4o3jpqmmBRMo1GWGQ0PsT5ezdDO7yig8Vie812VbrMpiSv1/9tG3eiQZBGqY3ANq5CaEuRuiSTC/XD7Ny7zN0+Npy8boJGum2aw/H0SXWUAnjyJ9ISIb1GYFcWkgSfxdkTc9YuGV13kbUrb5KHVz0aVVjzQhCOkvBsEQpgPAG00PEauEvEZxNdWl7o1sYPH2Rx2idpuJ98DYkXfnLxxhhOXtnDmH4a54DPrB47sDrsXjL7LVisTRczX0k/S1+Bkn26/f351YCIy704BhuhxmeyLNmF3knW9h52b5s6JuWjg4kwwCfzJb9JrdjkNNZx1G7U+Y4TrzAn73WdO6XJalOzAcDZ/RsBak3nmEOj6fY/pvpnD1sjKrIxbmpCrXi+WQldr0tqhf/3355PYQrMvhA7Ef9uE8vtshQZfOnrLWlj2lFU7crabViNCHzGpcIdxiUode/H/rnDrD7ENxn/7wZzVUdFGJtRr9RrG0LW8pfNDVHQrFdXafLLeaXgUSm2U20eb190ZLLdLXROv98Okao/409mxSt4llImubOjbosdqDwFDxcLoxcM9ASJOPUsL9spjBOLy+btp8IYzx+heVJ2VBbOsafJEti/O8ad9Ub3PE82S/vn4kbV3yppmV/y8NpwuM/sZQ5D1dfNEX0sHyMqun86zeWmTv7rw3pE5o+2HAPInzBv+1gojeBP5cBZj/L5+/brD3PtC+8QDONxU/pOAq6N8IuY+A/SzEoB8yEsPkNeYzK0mVNm1NyrRnb19SKD0tVlkZjrhvCm7DhhiNBdj95mm+ypfgr87YbtPVRstnAXfoetP43zOM7ccS3VmLRrKbAlkxNp99NJtUNMXC1vplP4jrwjeM2ANvvZYI9KEI8Wc7BA6R9Z3dW0S8sVD5ZyfG7fsNxEbrpc2wExM3xYUDgXz7Mp8GDGTbnC3PK8PKHYxMk47u+yJvsxlx13HdFufZtKWvp3nTcLLrJ7NyTU1OF5N8drb8ct2u1i0NOV9MymufGJCHTf1zIL/Mpx7Oj79ccQb2mxgCoVnQEPIvl0/WRTmzeD+LaOsBEBA0NU2YyxYm6uLaQnpRLW8JSMn31OiHN/liRcnmvPly+Tq7zIdxu5mGIcUePy0yFlqPgvKJYvI6o569LqgD/w3XH/1J7ErLO0f/TwAAAP//OK3aolMaAAA="; }
        }
    }
}
